week5/moma-app/config/routes.rb
Rails.application.routes.draw do

  # root page (get '/')
  root to: 'pages#home'

  # Artist CRUD

  # CREATE

  # 1. Blank form
  get '/artists/new' => 'artists#new', as: 'new_artist'

  # 2. Form submit, create artist, redirect to index
  post '/artists' => 'artists#create'

  # READ

  # 1. Index of all artists
  get '/artists' => 'artists#index'

  # 2. Show/details page for one artist by ID
  get '/artists/:id' => 'artists#show', as: 'artist'  # artist_path(ID)


  # UPDATE 

  # 1. Pre-filled form based on the artist ID
  get '/artists/:id/edit' => 'artists#edit', as: 'edit_artist'

  # 2. Form submit, perform update, redirect to show page
  patch '/artists/:id' => 'artists#update'

  # DESTROY
  delete '/artists/:id' => 'artists#destroy'


  # CRUD routes for Works
  resources :works
  
  #     works GET    /works(.:format)            works#index
  #           POST   /works(.:format)            works#create
  #  new_work GET    /works/new(.:format)        works#new
  # edit_work GET    /works/:id/edit(.:format)   works#edit
  #      work GET    /works/:id(.:format)        works#show
  #           PATCH  /works/:id(.:format)        works#update
  #           PUT    /works/:id(.:format)        works#update
  #           DELETE /works/:id(.:format)        works#destroy



end

week5/moma-app/app/models/artist.rb
class Artist < ApplicationRecord
  # Tell AR to look at the 'artist_id' column
  # of the 'works' table, to find out which
  # works belong to a certain artist
  # We can now say e.g.: a1.works 
  has_many :works
end

week5/moma-app/app/models/work.rb
class Work < ApplicationRecord
  # Tell AR to use the 'artist_id' of this
  # 'works' table to find the artist associated
  # with this artwork
  # We can now say e.g.:  w1.artist 
  belongs_to :artist
end

week5/moma-app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  # CREATE
  
  def new
    @artist = Artist.new  # No ID yet, i.e. create
  end

  def create
    # raise 'hell'  # debugging - lets us see 'params'

    # After lunch: how to reduce this repetition using a 'doorman'
    # Artist.create(
    #   name: params[:artist][:name],
    #   nationality: params[:artist][:nationality],
    #   dob: params[:artist][:dob],
    #   period: params[:artist][:period],
    #   bio: params[:artist][:bio],
    #   roundness: params[:artist][:roundness],
    #   image: params[:artist][:image]
    # )

    Artist.create artist_params # filtered list of fields

    redirect_to artists_path  # back to /artists index page

  end  # create


  # READ

  def index
    @artists = Artist.all
  end

  # i.e. GET /artists/:id
  def show
    @artist = Artist.find params[:id]
  end

  # UPDATE

  # 1. Pre-filled form, based on artist ID
  def edit
    @artist = Artist.find params[:id]
  end

  def update
    # raise 'hell'
    artist = Artist.find params[:id]

    artist.update artist_params 

    redirect_to artist_path(artist.id)
  end

  def destroy
    # raise 'hell'
    Artist.destroy params[:id]

    redirect_to artists_path   # back to index
  end

  # 'private' in general OOP means methods which are not
  # visible/callable from 'outside' the class, i.e. can't be
  # called on an object made from the class - they can only
  # be called by other methods within the class

  # What it means in a Rails controller is that this method
  # is NOT an 'action' - it's not a handler for a route, it's
  # just a toolkit function to be used by the actions 
  # (route-handling methods)
  

  private ##################################################

  # this method will return a special locked-down/'whitelisted'
  # version of params - only the specified keys within the
  # params hash will be allowed through - and then we can
  # use this version of params directly with Artist.create etc
  def artist_params
    # GOTCHA: if you add new columns to your table, they
    # will also have to be named here
    params.require(:artist).permit(:name, :nationality, :dob, :period, :roundness, :bio, :image)
  end


end # class ArtistsController

week5/moma-app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

end

week5/moma-app/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def new
    @work = Work.new
  end

  def create
    Work.create! work_params
    redirect_to works_path  # back to index /works
  end

  def index
    @works = Work.all
  end

  def show
    @work = Work.find params[:id]
  end

  def edit
    @work = Work.find params[:id]
  end

  def update
    work = Work.find params[:id]
    work.update work_params

    # Back to show page, i.e. /works/5 or whatever
    redirect_to work_path(work.id) 
  end

  def destroy
    Work.destroy params[:id]
    redirect_to works_path # index
  end

  private

  def work_params
    params.require(:work).permit( :title, :year, :medium, :style, :image, :artist_id )
  end

end # class WorksController

week5/moma-app/app/helpers/artists_helper.rb
module ArtistsHelper
end

week5/moma-app/app/helpers/works_helper.rb
module WorksHelper
end

week5/moma-app/app/views/artists/_form.html.erb
<%= form_with model: @artist, local: true do |f| %>

  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br><br>
  
  <%= f.label :nationality %>
  <br>
  <%= f.text_field :nationality %>
  <br><br>

  <%= f.label :dob, 'Date of Birth' %>
  <br>
  <%= f.date_field :dob %>
  <br><br>
  
  <%= f.label :period %>
  <br>
  <%= f.text_field :period %>
  <br><br>

  <%= f.label :roundness %>
  <br>
  <%= f.number_field :roundness, in: 1..10 %>
  <br><br>

  <%= f.label :bio %>
  <br>
  <%= f.text_area :bio %>
  <br><br>
  
  <%= f.label :image %>
  <br>
  <%= f.text_field :image, placeholder: 'URL here' %>
  <br><br>

  <%= f.submit %>

<% end %>

week5/moma-app/app/views/artists/edit.html.erb
<h2>Editing "<%= @artist.name %>"</h2>

<%= render partial: 'form' %>

week5/moma-app/app/views/artists/index.html.erb
<h2>All Artists</h2>

<ul>
<% @artists.each do |artist| %>

  <li>
    <%= link_to artist.name,   artist_path(artist.id) %>
    <!--        'Lee Krasner', /artists/13           -->
  </li>

<% end %>
</ul>

week5/moma-app/app/views/artists/new.html.erb
<h2>Add New Artist</h2>

<!-- load in a fragment of a template to use here -->
<%= render partial: 'form' %>

week5/moma-app/app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>

<!--                /artists/5/edit          -->
<%= link_to 'Edit', edit_artist_path(@artist.id) %>
|
<%= link_to 'Delete', artist_path(@artist.id), method: 'delete' %>

<p>
  <strong>Nationality:</strong>
  <%= @artist.nationality %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @artist.dob %>
</p>

<p>
  <strong>Period:</strong>
  <%= @artist.period %>
</p>

<p>
  <strong>Roundness:</strong>
  <%= @artist.roundness %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>
</p>

<%= image_tag @artist.image, alt: @artist.name, class: 'artist_image' %>

week5/moma-app/app/views/works/_form.html.erb
<%= form_with model: @work, local: true do |f| %>

  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br><br>
  
  <%= f.label :year %>
  <br>
  <%= f.text_field :year %>
  <br><br>
  
  <%= f.label :medium %>
  <br>
  <%= f.text_field :medium %>
  <br><br>
  
  <%= f.label :style %>
  <br>
  <%= f.text_field :style %>
  <br><br>

  <%= f.label :image, 'Image URL' %>
  <br>
  <%= f.text_field :image %>
  <br><br>

  <%= f.label :artist_id, 'Artist' %>
  <%= f.collection_select :artist_id, Artist.all, :id, :name, include_blank: true  %>

  <!-- 
  <option value="5">Lee Kranser</option>
  -->

  <br><br>

  <%= f.submit %>

<% end %>

week5/moma-app/app/views/works/edit.html.erb
<h2>
  Editing <%= @work.title %>
</h2>

<%= render partial: 'form' %>

week5/moma-app/app/views/works/index.html.erb
<h2>Index of Works</h2>

<ul>
<% @works.each do |work| %>
  <li>
    <%= link_to work.title, work_path(work.id) %>
  </li>
<% end %>
</ul>

week5/moma-app/app/views/works/new.html.erb
<h2>Add New Work</h2>

<%= render partial: 'form' %>

week5/moma-app/app/views/works/show.html.erb
<h2>
  <em><%= @work.title %></em>,
  <%= @work.year %>
</h2>
<h3>
  by 
  <%= link_to @work.artist.name, artist_path(@work.artist.id) %>
</h3>



<%= link_to 'Edit', edit_work_path(@work.id) %>
|
<%= link_to 'Delete', work_path(@work.id), method: 'delete' %>

<p>
  <strong>Medium:</strong>
  <%= @work.medium %>
</p>

<p>
  <strong>Style:</strong>
  <%= @work.style %>
</p>

<%= image_tag @work.image, alt: @work.title, class: 'artwork' %>