week5/tunr-db/config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  # Login/logout (session) routes
  get  '/login'   => 'session#new'     # show login form
  post '/login'   => 'session#create'  # form submit, perform login, redirect
  delete '/login' => 'session#destroy' # logout link goes here, perform logout, redirect

  # API endpoint for loading mixtapes as JSON (into map)
  get '/mixtapes/locations' => 'mixtapes#get_locations'

  
  resources :mixtapes, :users


end

week5/tunr-db/app/models/mixtape.rb
class Mixtape < ApplicationRecord
  has_and_belongs_to_many :songs
  belongs_to :user, optional: true 

  # Can't leave names blank for a mixtape!
  # Otherwise there's no link text to click on
  validates :name, presence: true

  # GEOCODING: automatically lookup the GPS coordinates for the address
  # of a mixtape, as it is .created

  geocoded_by :address

  after_validation :geocode  # actually do lookup when .create-ing

end

week5/tunr-db/app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  
  # Index and Show don't require a user to be logged in,
  # but all the other actions do (create, update, destroy)
  before_action :check_if_logged_in, except: [ :index, :show, :get_locations ]

  # For React map
  def get_locations
    headers['Access-Control-Allow-Origin'] = '*'  # Deal with CORS check
    render json: Mixtape.all
  end


  def new
    @mixtape = Mixtape.new
  end

  def create

    raise 'hell'  # so we can inspect 'params'

    # DO NOT SEND user_ids THROUGH A FORM! Anyone can change form data
    # from the dev tools!
    # Use @current_user.id here to associate with a user - this assumes
    # that the current action is locked down by 
    #   before_action :check_if_logged_in

    # Option 2. Use .new instead of .create, and 
    # then use '=' and '.save'
    @mixtape = Mixtape.new mixtape_params
    @mixtape.user_id = @current_user.id

    # Check if a file was uploaded via the form, and if so,
    # forward that file onto cloudinary,
    # and then save the file ID it gives us back, into the
    # mixtapes object
    if params[:mixtape][:image].present?
      # Upload to Cloudinary and capture the response, which includes a new ID
      response = Cloudinary::Uploader.upload params[:mixtape][:image]
      # p response  # view in iTerm/terminal

      # set the ID into the model object to save
      @mixtape.image = response["public_id"]  
    end # image upload

    # NOTE: for the 'update', be sure to remove
    # the image field from your strong params 
    # - otherwise you might overwrite the Cloudinary ID 
    # if you perform your @mixtape.update mixtape_params 
    # after the Cloudinary upload


    @mixtape.save  # this is actually the create, the DB insert

    # Option 1. Make a separate DB query using the '<<' syntax
    # @current_user.mixtapes << @mixtape

    if @mixtape.persisted?
      redirect_to mixtapes_path
    else
      render :new
    end  # else


  end  # create

  def index
    @mixtapes = Mixtape.all
  end

  def show
    @mixtape = Mixtape.find params[:id]
  end

  def edit
    @mixtape = Mixtape.find params[:id]

    # Don't even show the edit form if the
    # mixtape doesn't belong to this user

    # TODO: model method in app/models/user.rb:
    # if @current_user.owns( @mixtape )

    if @mixtape.user_id != @current_user.id
      redirect_to login_path
    end

  end


  def update

    @mixtape = Mixtape.find params[:id]

    # Check AGAIN that this mixtape belongs
    # to the logged-in user, since people can
    # still work out the edit URL even if they
    # aren't shown it 
    if @mixtape.user_id != @current_user.id
      redirect_to login_path
      return 
      # STOP THE REST OF THE CODE FROM RUNNING
      # i.e. prevent .update that follows
      #
      # Note: a redirect_to does NOT on its own
      # prevent the rest of the controller action's
      # code from running
    end

    if @mixtape.update mixtape_params
      redirect_to @mixtape  # defaults to show
    else
      render :edit
    end # else


  end  # update

  def destroy
  end

  private

  def mixtape_params
    params.require(:mixtape).permit(:name, :image) # REMOVE :image when using Cloudinary
  end

end # class

week5/tunr-db/app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

week5/tunr-db/app/views/mixtapes/_form.html.erb
<% if @mixtape.errors.any? %>
  <strong>Please correct the following:</strong>
  <ul>
    <% @mixtape.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @mixtape, local: true, html: { multipart: true } do |f| %>

  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <br>

  <%= f.label :image %>
  <br>
  <%= f.file_field :image %>
  <br>
  <br>

  <%= f.submit %>

<% end %>

week5/tunr-db/app/views/mixtapes/edit.html.erb
<h2>
  Editing Mixtape: <%= @mixtape.name %>
</h2>

<%= render partial: 'form' %>

week5/tunr-db/app/views/mixtapes/index.html.erb
<h2>All Mixtapes</h2>

<p>
  Total: <%= pluralize(@mixtapes.length, 'tape') %>
</p>

TODO: show only mixtapes belonging to current user?

<ul>
<% @mixtapes.each do |mixtape| %>
  <li>
    <%= link_to mixtape.name, mixtape_path(mixtape)  %>
    (<%= link_to mixtape.user.name, user_path(mixtape.user) %>)
  </li>
<% end %>
</ul>

week5/tunr-db/app/views/mixtapes/new.html.erb
<h2>Create Mixtape</h2>

<%= render partial: 'form' %>

week5/tunr-db/app/views/mixtapes/show.html.erb
<h2>
  Mixtape: <%= @mixtape.name %>
</h2>

<p>
  <em>
    Last updated <%= time_ago_in_words(@mixtape.updated_at) %> ago
    <br>
    Last Updated at <%= @mixtape.updated_at.strftime '%A %e %b, %Y %l:%M%P' %>
  </em>
</p>

<% if @current_user.present? && @current_user.id == @mixtape.user_id %>
  <%= link_to 'Edit', edit_mixtape_path(@mixtape) %>
<% end %>

<p>
  Song list here!
</p>

<% if @mixtape.image.present? %>
  <%= cl_image_tag @mixtape.image, alt: @mixtape.name %>
<% end %>