week5/planets-db/config/routes.rb
Rails.application.routes.draw do

  # for '/'
  root to: 'planets#home'

  # Planets CRUD


  # Create

  # 1. Blank form
  get '/planets/new' => 'planets#new', as: 'new_planet'  # new_planet_path()

  # 2. Form submits here, create planet, redirect to index
  post '/planets' => 'planets#create'

  # Read

  # 1. Index page of all planets

  get '/planets' => 'planets#index'

  # 2. Show/details page of one planet by ID
  get '/planets/:id' => 'planets#show', as: 'planet'
                                        # gives us 'planet_path()' as a helper


  # Update

  # 1. Pre-filled form (i.e. requires Planet.find with params[:id])
  get '/planets/:id/edit' => 'planets#edit', as: 'edit_planet'

  # 2. Form submits here, update existing planet, redirect to show
  patch '/planets/:id' => 'planets#update'


  # Delete

  # Delete planet by ID, redirect to index
  get '/planets/:id/delete' => 'planets#destroy', as: 'destroy_planet'  # destroy_planet_path( ID )


end

week5/planets-db/app/models/planet.rb
class Planet < ApplicationRecord

    # associations go here

    # also 'business logic' custom methods

end # Planet

week5/planets-db/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def home
  end

  # CREATE

  # 1. blank form
  def new
    @planet = Planet.new
  end

  # 2. form submit, create, redirect
  def create
    # raise 'hell'

    # Because the 'form_with' helper created form input names like
    # name="planet[moons]" and name="planet[image_url]",
    # the posted form data we get in params is more nested:
    # to access the moons, you write 'params[:planet][:moons]' etc

    # TODO: make sure the planet was actually created!
    # i.e. validation + user feedback --- later in the week
    Planet.create(
      name:      params[:planet][:name],
      mass:      params[:planet][:mass],
      orbit:     params[:planet][:orbit],
      moons:     params[:planet][:moons],
      image_url: params[:planet][:image_url]
    )

    # The 'create' route should not show its own template due to issues
    # around reloading a page reached by a form POST submit
    # (i.e. duplicating the create action in the database)
    # ... so instead we redirect somewhere else

    redirect_to planets_path  # '/planets'

  end  # create



  # READ

  # 1. Index of all planets
  def index
    @planets = Planet.all
    # raise 'hell'
  end

  # 2. Show page for a planet by ID
  # get /planets/:id
  def show
    @planet = Planet.find params[:id]
  end

  # UPDATE

  # 1. Pre-filled form
  def edit
    @planet = Planet.find params[:id]
  end

  # 2. Form submits here, perform update, redirect

  def update
    # raise 'hell'

    # FIRST: use the id from the URL /planets/5 (:id)
    planet = Planet.find params[:id]

    planet.update(
      name:      params[:planet][:name],
      mass:      params[:planet][:mass],
      orbit:     params[:planet][:orbit],
      moons:     params[:planet][:moons],
      image_url: params[:planet][:image_url]
    )

    # Redirect to the show page for 
    # the planet we just updated
    redirect_to planet_path(planet.id)


  end # update

  # DELETE

  def destroy
    Planet.destroy params[:id]  # TODO: validate that the destroy worked
    redirect_to planets_path  # back to index
  end


end # class PlanetsController

week5/planets-db/app/views/planets/edit.html.erb
<h2>Editing <%= @planet.name %></h2>


<%= form_with model: @planet, local: true do |f| %> 

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    
    <%= f.label :orbit %>
    <%= f.text_field :orbit %>
    <br>

    <%= f.label :mass %>
    <%= f.text_field :mass %>
    <br>

    <%= f.label :moons %>
    <%= f.text_field :moons %>
    <br>

    <%= f.label :image_url, 'Image URL' %>
    <%= f.text_field :image_url %>
    <br>

    <%= f.submit %>


<% end %>

week5/planets-db/app/views/planets/home.html.erb
<h2>Your Tour of the Solar System Begins Here</h2>

week5/planets-db/app/views/planets/index.html.erb
<h3>All Planets</h3>

<ul>

<% @planets.each do |planet| %>
  <li>
    <!--
    <a href="/planets/<%= planet.id %>"><%= planet.name %></a>
    -->
    <!--
    <%= link_to planet.name, "/planets/#{ planet.id }" %>
    -->

    <%= link_to planet.name, planet_path(planet.id) %>
  
  </li>
<% end %> 

</ul>

week5/planets-db/app/views/planets/new.html.erb
<h2>Add New Planet</h2>

<%= form_with model: @planet, local: true do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    
    <%= f.label :orbit %>
    <%= f.text_field :orbit %>
    <br>

    <%= f.label :mass %>
    <%= f.text_field :mass %>
    <br>

    <%= f.label :moons %>
    <%= f.text_field :moons %>
    <br>

    <%= f.label :image_url, 'Image URL' %>
    <%= f.text_field :image_url %>
    <br>

    <%= f.submit %>


<% end %>

<!--
<form action="/planets" method="post">
  <label>
    Name: 
    <input type="text" name="name">
  </label>
  <button>Create Planet</button>
</form>
-->

week5/planets-db/app/views/planets/show.html.erb
<h2><%= @planet.name %></h2>

<%= link_to 'Edit', edit_planet_path(@planet.id) %>
|
<%= link_to 'Delete', destroy_planet_path(@planet.id) %>

<p>
  <strong>Mass:</strong>
  <%= @planet.mass %> earth masses
</p>

<p>
  <strong>Orbit:</strong>
  <%= @planet.orbit %> earth orbits
</p>

<p>
  <strong>Moons:</strong>
  <%= @planet.moons %>
</p>

<%= image_tag @planet.image_url, alt: @planet.name, class: 'planet' %>